title: Neel Shah # your name (or website title) here
logo: "images/Profile picture.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hello! I'm Neel, an aspiring Data Analyst with a passion for extracting insights from data.
  <br><br>
    Lifelong learner, skilled in math & programming, passionate about data analysis, enjoys tackling complex challenges & creating visualizations.
   <br><br>
  <a href="https://www.linkedin.com/in/neelshah10/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-H8BFJ6XEH0 # your Google Analytics tracking ID here
